BEGIN;

DROP TABLE IF EXISTS subscriptions, coaches, sent_alerts CASCADE;


CREATE TABLE coaches (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(32),
    email varchar(32) NOT NULL,
    created timestamp default current_timestamp
);

CREATE TABLE subscriptions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coach_id integer NOT NULL,
    league_id varchar(16) NOT NULL,
    season_id varchar(16) NOT NULL,
    team_name varchar(64) NOT NULL,
    active boolean,
    created timestamp default current_timestamp,
    FOREIGN KEY (coach_id) REFERENCES coaches (id)
);

CREATE TABLE sent_alerts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscription_id integer NOT NULL,
    sent_at timestamp default current_timestamp,
    game_date date,
    FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)
);

INSERT INTO coaches (name, email) VALUES ('Zapp Brannigan', 'deathby@snusnu.com');
INSERT INTO subscriptions(coach_id, league_id, season_id, team_name, active) values (1, '54397', '2146954', 'HOW I MEGGED YOUR MOTHER', true);

COMMIT;