BEGIN;

DROP TABLE IF EXISTS subscriptions, coaches, alerts CASCADE;


CREATE TABLE coaches (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(32),
    email varchar(32) NOT NULL,
    created date
);

CREATE TABLE subscriptions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coach_id integer NOT NULL,
    league_id integer NOT NULL,
    season_id integer NOT NULL,
    team_name varchar(64) NOT NULL,
    active boolean,
    created date,
    FOREIGN KEY (coach_id) REFERENCES coaches (id)
);

CREATE TABLE alerts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscription_id integer NOT NULL,
    send_date date,
    game_date date,
    FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)
);

COMMIT;