CREATE TABLE subscriptions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coach_id integer NOT NULL,
    league_id varchar(16) NOT NULL,
    season_id varchar(16) NOT NULL,
    team_name varchar(64) NOT NULL,
    active boolean,
    created timestamp default current_timestamp,
    FOREIGN KEY (coach_id) REFERENCES coaches (id)
);