CREATE TABLE sent_alerts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscription_id integer NOT NULL,
    sent_at timestamp default current_timestamp,
    game_date date,
    FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)
);