name: Deploy Cloud Function
on:
  push:
    branches:
      - main
      - test-deploy
jobs:
  Deploy-Cloud-Function:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_DEPLOY_KEY }}"
      - run: echo "Deploying cloud function"
      - name: "Deploy"
        timeout-minutes: 5
        uses: "google-github-actions/deploy-cloud-functions@v3"
        with:
          name: "SendGameAlert"
          runtime: "go122"
          region: "us-west1"
