name: Run Function
on:
  push:
    branches:
      - test-run-function
jobs:
  Run-Function:
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22'
      - run: go run cmd/test/test.go | jq .
      - run: go run cmd/test/test.go > test.txt
      - run: cat test.txt | jq .
