name: Run Function
on:
  push:
    branches:
      - test-run-function
jobs:
  Run-Function:
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22'
      - run: go run cmd/test/test.go > output.txt
      - run: cat output.txt | jq .
        with:
          environment_variables: |-
              SFTP_PASS=${{ secrets.SFTP_PASS }}
              SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
              TO_EMAIL=${{ secrets.TO_EMAIL }}
              ENV=prod
              DATABASE_USER=${{ secrets.DATABASE_USER }}
              DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
              DATABASE_HOST=${{ secrets.DATABASE_HOST }}
              DATABASE_NAME=postgres
              DATABASE_PORT=5432
