name: Send Game Alerts
on:
  schedule:
    # This runs every day at 17:00 UTC
    - cron: '0 17 * * *'
  push:
    branches:
      - 'main'
jobs:
  send-game-alerts:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22'
      - name: Install dependencies
        run: go install .
      - name: Run game alerts script
        run: go run . | tee output.txt | jq . && exit ${PIPESTATUS[0]}
        env:
          ENV: prod
          SFTP_EMAIL: ${{ secrets.SFTP_EMAIL }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      - name: Send logs to aggregator
        if: always()
        run: echo "TODO"
              
