name: Send Game Alerts
on:
  schedule:
    # This runs every day at 17:00 UTC (9am pacific)
    - cron: '0 17 * * *'
  push:
    branches:
      - main
      - test-action
jobs:
  send-game-alerts:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Setup go
        uses: actions/setup-go@v7
        with: 
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go install .
      - name: Run game alerts script
        run: go run . | tee output.txt | jq . && exit ${PIPESTATUS[0]}
        env:
          ENV: prod
          SFTP_EMAIL: ${{ secrets.SFTP_EMAIL }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
      - name: Commit changes
        run: |
          git config --global user.name 'Lucas Gregory'
          git config --global user.email 'lucitez@users.noreply.github.com'
          git commit -am "Update send history"
          git push
      - name: Send logs to aggregator
        if: always()
        run: echo "TODO"
              
