name: Send Game Alerts
on:
  schedule:
    # This runs every 20 minutes from 8AM-10PM PST. Time here is in UTC
    - cron: '*/20 16-23,0-6 * * *'
  push:
    branches:
      - main
jobs:
  send-game-alerts:
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22'
      - name: Install dependencies
        run: go install .
      - name: Run game alerts script
        run: go run . | tee output.txt
        env:
          ENV: prod
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: postgres
          DATABASE_PORT: 5432
              
